### ISSUE TITLE
`pairwiseAlignment()` moved to pwalign warning in Biostrings >= 2.72.0

### ISSUE THREAD

**Issue by ecrespoSSF** [nanxstats/protr#52]
I was having issues with pairwise alignments using the crossSetSim() and parSeqSim() examples listed in the vignette https://cran.r-project.org/web/packages/protr/vignettes/protr.html#Similarity_calculation_by_sequence_alignment 

It wasn't until I tried twoSeqSim() that I received this error:
<simpleError in .load_package_gracefully("pwalign", "starting with BioC 3.19, ",     "calling ", fun, "()"): Could not load package pwalign. Is it installed?

  Note that starting with BioC 3.19, calling pairwiseAlignment() requires the pwalign package.
  Please install it with:

    BiocManager::install("pwalign")>

Installing pwalign has fixed the issue using R version 4.4.1 (2024-06-14) -- "Race for Your Life" on this Platform: x86_64-apple-darwin20

**Comment by ecrespoSSF** [comment]
This function is still a problem
In .call_fun_in_pwalign("pairwiseAlignment", ...) :
  pairwiseAlignment() has moved to the pwalign package. Please call pwalign::pairwiseAlignment() to
  get rid of this warning.

**Comment by nanxstats** [comment]
Thanks for reporting. It seems the pairwise sequence alignment stuff has been moved from Biostrings to pwalign (https://github.com/Bioconductor/Contributions/issues/3361). I will make a CRAN update soon to fix this issue.

**Comment by nanxstats** [comment]
protr 1.7.3 is now on CRAN. You can use `install.packages("protr")` to try the new version. Use `type = "source"` if the binary is not built by CRAN yet.

In brief, the new behavior is:

- If Biostrings is not installed, there should be an error saying Biostrings is required and should be installed from Bioconductor.
- If you have Bioconductor >= 3.19 and Biostrings >= 2.72.0 without pwalign installed, there should be an explicit error in the results saying pwalign is required and should be installed from Bioconductor.
- If a lower version of Biostrings is installed (possibily due to using a lower version of R and Bioconductor), then things should work as before.
